# Generated by Django 4.1.3 on 2022-11-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googel_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuesearch',
            name='title',
        ),
    ]
