# Generated by Django 4.1.3 on 2022-11-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googel_search', '0002_remove_valuesearch_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuesearch',
            name='titles',
            field=models.CharField(max_length=255000),
        ),
        migrations.AlterField(
            model_name='valuesearch',
            name='urls',
            field=models.CharField(max_length=255000),
        ),
    ]
