# Generated by Django 4.1.3 on 2022-11-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googel_search', '0003_alter_valuesearch_titles_alter_valuesearch_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuesearch',
            name='titles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='valuesearch',
            name='urls',
            field=models.TextField(),
        ),
    ]
