# Generated by Django 4.1.3 on 2022-11-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googel_search', '0004_alter_valuesearch_titles_alter_valuesearch_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuesearch',
            name='title',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
