# Generated by Django 4.1.3 on 2022-11-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=255)),
                ('urls', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_box', models.CharField(max_length=300)),
                ('number', models.SmallIntegerField()),
            ],
        ),
    ]
